### ISSUE TITLE
descarteslabs conda package has a dependency on old version of cloudpickle

### ISSUE THREAD

**Issue by jeverling** [conda-forge/descarteslabs-feedstock#40]
Hi, the dependencies on cloudpickle in [setup.py](https://github.com/descarteslabs/descarteslabs-python/blob/master/setup.py) for [descarteslabs-python](https://github.com/descarteslabs/descarteslabs-python/) are:

            "cloudpickle==0.4.0;python_version<'3.8'",
            "cloudpickle==1.6.0;python_version>='3.8'",

However, this package has a hard dependency on `cloudpickle==0.4.0`, regardless of the Python version in use.
From version 1.4.0, cloudpickle requires at least Python 3.5, I don't know whether it's safe to just use version 1.6.0 with all newer versions of Python 3.

But 0.4.0 is from May 2017 and it's probably preferable to not install this old version. I don't know whether it's possible to specify different dependency versions for different interpreters in conda like it's done in the setup.py, but I think it might work to just use 1.6.0 because it should work with all modern versions of Python.

**Comment by ocefpaf** [comment]
> I don't know whether it's possible to specify different dependency versions for different interpreters in conda like it's done in the setup.py, but I think it might work to just use 1.6.0 because it should work with all modern versions of Python.

It is easy but trying to do that opened a can of worms! this package depends on a really old `pyarrow` and I could nor re-created the package as a no-noarch version so we can depend on different versions of the dependencies for each Python.

How broken are things on your end? Maybe we can wait for a new release and hope they upgrade to latest pyarrow.
